### PR TITLE
Add Installation instructions

### PR DESCRIPTION
**Pull request by wanacode**
I have helped a number of people get started using OpenOrienteering Mapper and one of the most frequent questions was needing help on how to install the software.

I propose to add an installation page to be able to point people to for instructions. I am not familiar with installing on Android or macOS so the page may need more help added.

### CODE REVIEW

**Comment by dg0yt** [comment]
What do you think about extending the [Mapper homepage](https://www.openorienteering.org/apps/mapper/) in this regard?

**Comment by wanacode** [comment]
If you don't want to include it in the manual then that is probably the next best place. You could possibly add a link on the Contents page under "Online resources" to the installation instructions.

However, by not including it in the manual it will mean others can't contribute to the documentation in future. I thought having installation instructions as part of a manual is pretty standard. Anyway, I am happy to point people to my installation page if needed. I added a bit more info: https://wanacode.github.io/mapper-manual/pages/installation.html

Thanks

**Comment by dg0yt** [comment]
Thanky you very much. I'm fine with adding to the manual, and it already looks very good to me. 

Some people look at manuals only after installation. By including it in the homepage, we might even offer a basic detection of the OS. And even the homepage can be contribute to ;-)

Possible extensions:
- Changing OS settings for unsigned application/apps from unknown sources
- Windows: when to use x86 instead
- macOS: How to proceed with the DMG

**Comment by Fardiansyah88** [comment]
https://github.com/OpenOrienteering/mapper-manual/commit/b9bc7c10210bfd512a63537079b61ba16e76afb5?short_path=eeed4bf#commitcomment-35273044

**Pull request merged**
