### PR TITLE
Update android-requirements.md

### PR DESCRIPTION
**Pull request by dg0yt**
Another app for external GNSS added as mentioned by Remo:
https://github.com/OpenOrienteering/mapper/issues/1596

### CODE REVIEW

**Comment by dg0yt** [comment]
@ollesmaps I guess this is meant to be merged quickly, for the online manual?

**Comment by ollesmaps** [comment]
@dg0yt That is right.

**Comment by ghost** [comment]
What about reference *GPSTest* app for testing purposes?

- https://github.com/barbeau/gpstest

Also, as I can see only two apps from Google Play referenced:

```
For example the [Bluetooth GPS app](https://play.google.com/store/apps/details?id=googoo.android.btgps&rdid=googoo.android.btgps) or [Bluetooth GNSS app](https://play.google.com/store/apps/details?id=com.clearevo.bluetooth_gnss) provide a "mock" location provider which can be used when Android is put in developer mode.
```

But what about reference similar apps from F-Droid?

- https://f-droid.org/packages/ru0xdc.rtkgps/
- https://f-droid.org/packages/org.broeuschmeul.android.gps.bluetooth.provider/
- https://f-droid.org/packages/org.broeuschmeul.android.gps.usb.provider/

**Comment by lpechacek** [comment]
@Symbian9, I don't think this manual section was ever meant to be a *complete* list of applications. I'm all for keeping it at the "useful hint" level.

**Pull request closed without merging**
